language: node_js

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

before_install:
 - ls
 
install:
- npm install --save-dev
- npm i mocha --save-dev
- npm i electron-builder --save-dev

script:
- ./node_modules/.bin/build
- ./node_modules/.bin/mocha