matrix:
  include:
    - os: linux
      language: node_js
      node_js: "4"
    - os: osx
      osx_image: beta-xcode6.2
      language: node_js
      node_js: "4"
    - os: osx
      osx_image: xcode7.3
      language: node_js
      node_js: "4"
    - os: osx

before_install:
  - ls 
  
install:
  - npm install --save-dev electron
  - npm install --save-dev electron-builder
  - npm install --save-dev mocha 
  - npm install --save-dev spectron

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - ./node_modules/.bin/build
  - ls dist 
  - ./node_modules/.bin/mocha