language: node_js
node_js:
  - "4"
  
sudo: required
dist: trusty

matrix:
  include:
    - os: osx
    - os: linux

before_install:
  - ls
 
install:
  - npm i electron --save-dev
  - npm i electron-builder --save-dev
  - npm i mocha --save-dev

script:
  - ./node_modules/.bin/build
  - ./node_modules/.bin/mocha